/**
 * The few instruments that are carried as audio rather than synthesised.
 *
 * Almost everything in this engine is computed from numbers, and that is the point of it. Three
 * sounds defeat it: the reference module's chord stabs are *chords*, recorded whole, so there is
 * no single tone for a patch to match — handed to an oscillator they come out as one bare note
 * where the original has a triad, which is heard as the wrong chord rather than a plainer one.
 *
 * The data is generated by `npm run music:transcribe -- --samples=15,16,17`; see `scores/`.
 */
import { FOREGONE_SAMPLES } from './scores/foregoneSamples.ts';

/** One sound as it is stored: 8-bit unsigned PCM, base64. */
export interface RawSample {
  /** Frames per second the PCM is stored at. */
  readonly rate: number;
  /** MIDI note it sounds when played back at `rate`; other notes are a ratio from here. */
  readonly root: number;
  readonly frames: number;
  readonly pcm: string;
}

export interface LoadedSample {
  readonly rate: number;
  readonly root: number;
  readonly data: Float32Array;
}

/** Decoded on first use, not at import: a soundtrack nobody selects costs nothing. */
const loaded = new Map<string, LoadedSample>();

export type SampleName = keyof typeof FOREGONE_SAMPLES;

export function isSampleName(name: string): name is SampleName {
  return name in FOREGONE_SAMPLES;
}

export function sampleFor(name: SampleName): LoadedSample {
  const cached = loaded.get(name);
  if (cached) return cached;

  const raw = FOREGONE_SAMPLES[name];
  const bytes = decodeBase64(raw.pcm);
  const data = new Float32Array(raw.frames);
  for (let i = 0; i < raw.frames; i++) data[i] = (bytes[i] - 128) / 127;

  const sample = { rate: raw.rate, root: raw.root, data };
  loaded.set(name, sample);
  return sample;
}

/** `atob` is on `window` and this also runs in a worker and in Node, so it is spelled out. */
function decodeBase64(text: string): Uint8Array {
  const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
  const lookup = new Uint8Array(128);
  for (let i = 0; i < alphabet.length; i++) lookup[alphabet.charCodeAt(i)] = i;

  const padding = text.endsWith('==') ? 2 : text.endsWith('=') ? 1 : 0;
  const out = new Uint8Array((text.length / 4) * 3 - padding);
  let at = 0;
  for (let i = 0; i < text.length; i += 4) {
    const chunk = (lookup[text.charCodeAt(i)] << 18)
      | (lookup[text.charCodeAt(i + 1)] << 12)
      | (lookup[text.charCodeAt(i + 2)] << 6)
      | lookup[text.charCodeAt(i + 3)];
    if (at < out.length) out[at++] = (chunk >> 16) & 0xff;
    if (at < out.length) out[at++] = (chunk >> 8) & 0xff;
    if (at < out.length) out[at++] = chunk & 0xff;
  }
  return out;
}
