/**
 * Playing music taken apart from a real piece rather than invented or replayed.
 *
 * A `LoopScore` is a tracker module dismantled: every distinct four bars any one instrument plays,
 * once each, plus which instruments were heard together and where the harmony moves. That is the
 * module's musical content without its running order — enough to build arrangements it never
 * played, and deliberately not enough to play back the one it did.
 *
 * A `ScoreVoice` says what one of its instruments *is*: which synth patch plays it, which layer it
 * belongs to for the intensity gate, and how far to move it.
 *
 * That last number is not optional. A tracker note is a playback *rate*, not a pitch: a sample
 * whose own tone is two octaves below where it was recorded sounds two octaves below what the
 * pattern says. Play the written numbers and you get the right rhythm in the wrong key, with the
 * parts in the wrong registers relative to each other — which is a different piece of music.
 */
import type { EventKind } from './notes.ts';
import type { MusicLayer } from './themes.ts';

/** Loops as extracted. Generated by `npm run music:transcribe`; see `scripts/umxTranscribe.ts`. */
export interface LoopScore {
  readonly title: string;
  readonly bpm: number;
  /** Rows in one loop. Four rows to the beat, so 64 rows is four bars. */
  readonly rows: number;
  /** Every distinct four bars one instrument plays, once each. */
  readonly loops: readonly ScoreLoop[];
  /** The stretches of the original whose harmony holds still. */
  readonly sections: readonly LoopSection[];
}

export interface ScoreLoop {
  /** The module's instrument number — `scores.ts` says what it sounds like. */
  readonly instrument: number;
  /** `row,note,volume,rows,pan` per note, space separated. */
  readonly notes: string;
}

/**
 * A stretch of the original whose harmony holds still, so anything in it fits anything else in it.
 *
 * Its `cells` are four bars each and play in order. One cell is a section that stays where it is;
 * the strings' four are a chord progression, the one thing in this piece that cannot be shuffled.
 */
export interface LoopSection {
  readonly name: string;
  readonly cells: readonly LoopCell[];
}

/** What four bars of a section may contain. */
export interface LoopCell {
  /**
   * Instrument sets heard together in the original, as `1,5,14,18`, fewest instruments first.
   *
   * The orchestration, extracted rather than reasoned about — and the reason a generated
   * arrangement stays coherent. It is what stops both kicks landing in one bar, or the hook
   * playing over a drone it never shared a bar with.
   */
  readonly voicings: readonly string[];
  /** Which loops each instrument may play here, by instrument number. */
  readonly parts: Readonly<Record<number, readonly number[]>>;
}

/** What one of a score's instruments is, once something has to make a sound. */
export interface ScoreVoice {
  /** Which patch or drum plays it. */
  readonly kind: EventKind;
  /** Which layer it counts as, for the intensity gate and the per-theme mix. */
  readonly layer: MusicLayer;
  /** Semitones added to the written note — see the note above; rarely zero. */
  readonly transpose: number;
  /** Multiplies the note's transcribed volume. */
  readonly gain: number;
  /** Seconds a drum rings. Ignored by tuned patches, which are held for the written length. */
  readonly ring?: number;
}

/** A score and the reading of it. One score can only be played through one of these. */
export interface PlayableScore {
  readonly score: LoopScore;
  /** By instrument number, as the module numbers them. An instrument with no voice is silent. */
  readonly voices: Readonly<Record<number, ScoreVoice>>;
}
