/**
 * Playing music that was written down rather than generated.
 *
 * A `TrackerScore` is the note data of a tracker module — what note, on which channel, from which
 * instrument, how loud, how long — and nothing about sound. A `ScoreVoice` says what one of its
 * instruments *is*: which synth patch plays it, which layer it belongs to for the intensity gate,
 * and how far to move it.
 *
 * That last number is not optional. A tracker note is a playback *rate*, not a pitch: a sample
 * whose own tone is two octaves below where it was recorded sounds two octaves below what the
 * pattern says. Play the written numbers and you get the right rhythm in the wrong key, with the
 * parts in the wrong registers relative to each other — which is a different piece of music.
 */
import type { EventKind } from './notes.ts';
import { STEPS_PER_BEAT, type NoteEvent, type NoteSource } from './notes.ts';
import type { MusicLayer, ScoreTheme } from './themes.ts';

/** IT's volume scale, and the pan range the transcriber writes. */
const MAX_VOLUME = 64;
const MAX_PAN = 64;
/** What the transcriber writes for "this note says nothing about pan". */
const PAN_UNSET = 127;

/** Notes as transcribed. Generated by `npm run music:transcribe`; see `scripts/umxTranscribe.ts`. */
export interface TrackerScore {
  readonly title: string;
  readonly bpm: number;
  /** Rows per pattern. Four rows to the beat, so 64 rows is four bars. */
  readonly rows: number;
  /** Which pattern plays when, in order. */
  readonly orders: readonly number[];
  /** Pan per channel, -64…64. */
  readonly pans: readonly number[];
  /** One string per pattern: `channel,row,note,instrument,volume,rows,pan` per note. */
  readonly patterns: readonly string[];
}

/** What one of a score's instruments is, once something has to make a sound. */
export interface ScoreVoice {
  /** Which patch or drum plays it. */
  readonly kind: EventKind;
  /** Which layer it counts as, for the intensity gate and the per-theme mix. */
  readonly layer: MusicLayer;
  /** Semitones added to the written note — see the note above; rarely zero. */
  readonly transpose: number;
  /** Multiplies the note's transcribed volume. */
  readonly gain: number;
  /** Seconds a drum rings. Ignored by tuned patches, which are held for the written length. */
  readonly ring?: number;
}

/** A score and the reading of it. One score can only be played through one of these. */
export interface PlayableScore {
  readonly score: TrackerScore;
  /** By instrument number, as the module numbers them. An instrument with no voice is silent. */
  readonly voices: Readonly<Record<number, ScoreVoice>>;
}

interface ScoreNote {
  channel: number;
  note: number;
  instrument: number;
  volume: number;
  rows: number;
  pan: number;
}

/**
 * Reads a transcribed score onto the same sixteenth grid the composer writes on.
 *
 * The grid lines up exactly: a tracker at four rows to the beat *is* sixteenths, so one row is one
 * step and nothing has to be resampled in time.
 */
export class ScorePlayer implements NoteSource {
  private theme: ScoreTheme;
  private score: TrackerScore;
  private voices: Readonly<Record<number, ScoreVoice>>;
  /** `rows[pattern][row]` — decoded once, since the order list plays most patterns twice. */
  private rows: ScoreNote[][][];
  /** Rows in the stretch this mood loops. */
  private length: number;

  constructor(theme: ScoreTheme, playable: PlayableScore) {
    this.theme = theme;
    this.score = playable.score;
    this.voices = playable.voices;
    this.rows = playable.score.patterns.map(text => decodePattern(text, playable.score.rows));
    this.length = (theme.to - theme.from) * playable.score.rows;
  }

  get stepDuration(): number {
    return 60 / this.score.bpm / STEPS_PER_BEAT;
  }

  get beatDuration(): number {
    return 60 / this.score.bpm;
  }

  /** One pattern — four bars, and where the piece was already going to change. */
  get stepsPerChord(): number {
    return this.score.rows;
  }

  collect(step: number, intensity: number, out: NoteEvent[]): number {
    const at = ((step % this.length) + this.length) % this.length;
    const order = this.theme.from + Math.floor(at / this.score.rows);
    const pattern = this.rows[this.score.orders[order]];
    if (!pattern) return 0;

    let count = 0;
    for (const note of pattern[at % this.score.rows]) {
      if (count >= out.length) break;
      const voice = this.voices[note.instrument];
      if (!voice || !this.plays(voice.layer, intensity)) continue;
      this.write(out[count++], note, voice);
    }
    return count;
  }

  /** A layer plays if this theme lists it and the intensity has reached it. */
  private plays(layer: MusicLayer, intensity: number): boolean {
    const threshold = this.theme.layers[layer];
    return threshold !== undefined && intensity >= threshold;
  }

  private write(event: NoteEvent, note: ScoreNote, voice: ScoreVoice): void {
    const pan = note.pan === PAN_UNSET ? (this.score.pans[note.channel] ?? 0) : note.pan;
    event.kind = voice.kind;
    event.note = note.note + voice.transpose;
    event.duration = voice.ring ?? note.rows * this.stepDuration;
    event.velocity = (note.volume / MAX_VOLUME) * voice.gain
      * (this.theme.gains?.[voice.layer] ?? 1);
    event.pan = Math.max(-1, Math.min(1, pan / MAX_PAN));
    // Fixed per position rather than random, so the piece is the same piece every time round.
    event.seed = (note.channel * 2654435761 + note.rows * 40503 + note.note) >>> 1;
  }
}

/** `channel,row,note,instrument,volume,rows,pan` per note, space separated, into rows. */
function decodePattern(text: string, rowCount: number): ScoreNote[][] {
  const rows: ScoreNote[][] = Array.from({ length: rowCount }, () => []);
  if (text.length === 0) return rows;

  for (const part of text.split(' ')) {
    const [channel, row, note, instrument, volume, held, pan] = part.split(',').map(Number);
    rows[row].push({ channel, note, instrument, volume, rows: held, pan });
  }
  return rows;
}
